/**
 * An agent persona's icon: a lucide icon stored by name ("Bot", "Skull",
 * "Palette"). The curated palette custom agents were given; any other name
 * shows the robot.
 */
import type { LucideIcon } from "lucide-react";
import {
  Anchor,
  Apple,
  Atom,
  Bird,
  Bot,
  Brain,
  Briefcase,
  Bug,
  Cake,
  Camera,
  Cat,
  CircuitBoard,
  Code2,
  Coffee,
  Cog,
  Compass,
  Cpu,
  Crosshair,
  Crown,
  Dog,
  Dumbbell,
  Fish,
  Flame,
  FlaskConical,
  Gamepad2,
  Gem,
  Globe2,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Hexagon,
  Leaf,
  Lightbulb,
  Medal,
  Microscope,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  Palette,
  Pen,
  Rocket,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sticker,
  Sun,
  Swords,
  Target,
  Telescope,
  Trophy,
  UtensilsCrossed,
  Wand2,
  Wine,
  Zap,
} from "lucide-react";

const AGENT_ICONS: Record<string, LucideIcon> = {
  Bot: Bot,
  Skull: Skull,
  Sticker: Sticker,
  Apple: Apple,
  Brain: Brain,
  Lightbulb: Lightbulb,
  Flame: Flame,
  Zap: Zap,
  Shield: Shield,
  Swords: Swords,
  Sparkles: Sparkles,
  Palette: Palette,
  Music: Music,
  Gamepad2: Gamepad2,
  Camera: Camera,
  Telescope: Telescope,
  Rocket: Rocket,
  Atom: Atom,
  GraduationCap: GraduationCap,
  Briefcase: Briefcase,
  Hammer: Hammer,
  Microscope: Microscope,
  Leaf: Leaf,
  Dog: Dog,
  Cat: Cat,
  Bird: Bird,
  Bug: Bug,
  Fish: Fish,
  Crown: Crown,
  Gem: Gem,
  Star: Star,
  Moon: Moon,
  Sun: Sun,
  Mountain: Mountain,
  Anchor: Anchor,
  Compass: Compass,
  Crosshair: Crosshair,
  Target: Target,
  Trophy: Trophy,
  Medal: Medal,
  Dumbbell: Dumbbell,
  HeartPulse: HeartPulse,
  Coffee: Coffee,
  UtensilsCrossed: UtensilsCrossed,
  Wine: Wine,
  Cake: Cake,
  Paintbrush: Paintbrush,
  Pen: Pen,
  Wand2: Wand2,
  Hexagon: Hexagon,
  CircuitBoard: CircuitBoard,
  Cog: Cog,
  FlaskConical: FlaskConical,
  Heart: Heart,
  Code2: Code2,
  Globe2: Globe2,
  Cpu: Cpu,
};

/** Resolve an icon name string to its lucide component. */
export function resolveIconComponent(name: string): LucideIcon {
  if (!name) return Bot;
  return AGENT_ICONS[name] || Bot;
}
